spring:
  datasource:
    password: 12345
    url: jdbc:mysql://localhost:3306/biblioteca?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
  jpa:
    database: MYSQL
    generate-ddl: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: true